import SolvedProblemBadge from '../problems/SolvedProblemBadge';
import useSolvedProblemIds from '../../hooks/useSolvedProblemIds';
import { ArrowRight, Code2, Star, Loader2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { getDifficultyClasses } from '../../utils/theory';

export default function RelatedProblems({ problems, gradeId, section }) {
  const { solvedIds, loading, error } = useSolvedProblemIds(problems.map((problem) => problem.id));
  const sectionHref = gradeId && section ? `/probleme/clasa/${gradeId}/sectiune/${encodeURIComponent(section)}` : '/probleme';

  return <section className="mt-8 w-full min-w-0 overflow-hidden rounded-2xl border border-border bg-ink p-5 sm:p-6"><div className="flex min-w-0 flex-col justify-between gap-3 sm:flex-row sm:items-end"><div className="min-w-0"><div className="flex items-center gap-2 text-sm font-bold uppercase tracking-[0.16em] text-accent"><Code2 className="h-4 w-4 shrink-0" />Exersează ce ai învățat</div><h2 className="mt-3 break-words text-xl font-bold text-text-main">Probleme din acest capitol</h2></div><Link to={sectionHref} className="inline-flex w-fit max-w-full items-center gap-2 text-sm font-bold text-accent transition-colors hover:text-text-main"><span className="min-w-0 whitespace-normal">Vezi problemele din secțiune</span><ArrowRight className="h-4 w-4 shrink-0" /></Link></div>{error && <p role="alert" className="mt-4 text-sm text-muted">{error}</p>}{loading ? <div role="status" className="flex justify-center p-6"><Loader2 aria-hidden="true" className="h-5 w-5 animate-spin text-accent" /><span className="sr-only">Se încarcă problemele...</span></div> : problems.length === 0 ? <p className="mt-5 text-sm text-muted">Nu există probleme disponibile pentru acest capitol încă.</p> : <div className="mt-5 grid min-w-0 gap-3 md:grid-cols-2">{problems.map((problem) => <Link key={problem.id} to={`/rezolvare/${problem.id}`} className={`group min-w-0 max-w-full rounded-xl border ${solvedIds.has(String(problem.id)) ? 'border-easy/40' : 'border-border'} bg-background p-4 transition-colors hover:border-accent`}><div className="flex min-w-0 items-start gap-3"><span className="mt-0.5 shrink-0 rounded-lg bg-accent/10 p-2 text-accent"><Code2 className="h-4 w-4" /></span><div className="min-w-0 flex-1"><h3 className="truncate font-bold text-text-main transition-colors group-hover:text-accent">{problem.title}</h3>{problem.description && <p className="mt-1 line-clamp-2 text-xs leading-relaxed text-muted">{problem.description}</p>}<div className="mt-3 flex flex-wrap items-center gap-2"><SolvedProblemBadge isSolved={solvedIds.has(String(problem.id))} /><span className={`rounded-md border px-2 py-0.5 text-[10px] font-bold uppercase ${getDifficultyClasses(problem.difficulty)}`}>{problem.difficulty || 'Mixt'}</span><span className="inline-flex items-center gap-1 text-xs font-bold text-accent"><Star className="h-3 w-3 fill-current" />{problem.xp_reward || 0} XP</span></div></div></div></Link>)}</div>}</section>;
}
