export const THEORY_DRAFT_KEY = 'pylearn-theory-dev-draft';

export const THEORY_STARTER = [
  '# Titlul lecției',
  '',
  'O introducere scurtă, de 2–4 propoziții, care explică ce este conceptul și de ce este util.',
  '',
  '## Ce vei învăța',
  '',
  'La finalul acestei lecții vei ști:',
  '',
  '- să explici conceptul principal;',
  '- să folosești sintaxa corectă;',
  '- să aplici conceptul în probleme simple.',
  '',
  '## Explicație',
  '',
  'Explică ideea pas cu pas, folosind un limbaj simplu și exemple concrete.',
  '',
  'Evidențiază termenii importanți cu **bold**, iar elementele de cod cu `inline code`.',
  '',
  'Evită paragrafele foarte lungi. O idee importantă ar trebui explicată înainte de a trece la următoarea.',
  '',
  '## Sintaxă',
  '',
  'Forma generală este:',
  '',
  '```python',
  '# sintaxa de bază',
  '```',
  '',
  'Explică pe scurt fiecare parte importantă a sintaxei.',
  '',
  '## Exemplu',
  '',
  'Să analizăm un exemplu simplu:',
  '',
  '```python',
  '# exemplu static',
  'x = 10',
  'print(x)',
  '```',
  '',
  'Explică ce face programul, pas cu pas.',
  '',
  '## Încearcă singur',
  '',
  'Modifică valorile din editor și apasă **Rulează**.',
  '',
  '```python run',
  'x = 10',
  '',
  'print(x)',
  '```',
  '',
  'Încearcă să modifici valoarea lui `x` și observă rezultatul.',
  '',
  '## Exemplu practic',
  '',
  'Acum folosim conceptul într-un exemplu puțin mai apropiat de o problemă reală:',
  '',
  '```python run',
  'a = 5',
  'b = 7',
  '',
  'rezultat = a + b',
  '',
  'print(rezultat)',
  '```',
  '',
  'Încearcă să modifici valorile și să anticipezi rezultatul înainte de a rula programul.',
  '',
  '## Atenție',
  '',
  'Menționează aici greșelile frecvente sau situațiile importante pentru această lecție.',
  '',
  '- prima greșeală frecventă;',
  '- a doua greșeală frecventă.',
  '',
  '## Exercițiu rapid',
  '',
  'Încearcă să modifici codul astfel încât să rezolve următoarea cerință:',
  '',
  '**Scrie aici o cerință foarte scurtă care poate fi rezolvată în 1–3 minute.**',
  '',
  '```python run',
  '# Scrie sau modifică soluția aici',
  '```',
  '',
  '## De reținut',
  '',
  '- prima idee esențială;',
  '- a doua idee esențială;',
  '- a treia idee esențială;',
  '- regula sau sintaxa importantă.',
  '',
  '## Următorul pas',
  '',
  'Acum că ai înțeles conceptul, încearcă problemele asociate acestui capitol pentru a-l exersa.',
  '',
].join('\n');

export function lessonUpdateSql(markdown, lessonId) {
  if (!/^[1-9]\d*$/.test(lessonId) || BigInt(lessonId) > 9223372036854775807n) {
    throw new Error('Introdu un ID de lecție valid (număr întreg pozitiv).');
  }
  let tag = 'pylearn_lesson';
  for (let suffix = 1; markdown.includes(`$${tag}$`); suffix += 1) tag = `pylearn_lesson_${suffix}`;
  const delimiter = `$${tag}$`;
  return `update public.theory_lessons\nset content = ${delimiter}${markdown}${delimiter}\nwhere id = ${lessonId};`;
}
