-- PyLearn economy: XP remains permanent, while coins are earned from the same
-- trusted profile XP update that follows a first accepted problem submission.

alter table public.profiles
  add column if not exists coin_balance integer not null default 0;

alter table public.profiles
  add column if not exists total_coins_earned integer not null default 0;

alter table public.profiles
  add column if not exists economy_initialized_at timestamptz;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_coin_balance_nonnegative'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_coin_balance_nonnegative check (coin_balance >= 0);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_total_coins_earned_nonnegative'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table public.profiles
      add constraint profiles_total_coins_earned_nonnegative check (total_coins_earned >= 0);
  end if;
end;
$$;

-- Avatar URLs are deliberately not stored. The seed is rendered centrally by
-- the existing DiceBear utility in the frontend.
create table if not exists public.avatar_catalog (
  id bigint generated by default as identity primary key,
  name text not null,
  seed varchar(64) not null unique,
  gender_style text not null default 'neutral',
  price_coins integer not null default 0,
  required_level integer not null default 0,
  rarity text not null default 'common',
  is_active boolean not null default true,
  is_starter boolean not null default false,
  is_free boolean not null default false,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  constraint avatar_catalog_name_not_blank check (length(btrim(name)) > 0),
  constraint avatar_catalog_price_nonnegative check (price_coins >= 0),
  constraint avatar_catalog_level_nonnegative check (required_level >= 0),
  constraint avatar_catalog_gender_style_check check (gender_style in ('feminine', 'masculine', 'neutral')),
  constraint avatar_catalog_rarity_check check (rarity in ('common', 'rare', 'epic', 'legendary')),
  constraint avatar_catalog_free_price_check check (not is_free or price_coins = 0)
);

create table if not exists public.user_avatars (
  user_id uuid not null references public.profiles(id) on delete cascade,
  avatar_id bigint not null references public.avatar_catalog(id) on delete restrict,
  purchased_at timestamptz not null default now(),
  primary key (user_id, avatar_id)
);

create index if not exists user_avatars_avatar_id_idx
  on public.user_avatars (avatar_id);

create table if not exists public.coin_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  amount integer not null,
  transaction_type text not null,
  reason text not null,
  reference_id bigint,
  created_at timestamptz not null default now(),
  constraint coin_transactions_amount_nonzero check (amount <> 0),
  constraint coin_transactions_type_check check (transaction_type in ('earned', 'spent'))
);

create index if not exists coin_transactions_user_created_at_idx
  on public.coin_transactions (user_id, created_at desc);

-- The original 12 seeds are permanent starter avatars. Premium seeds are fixed
-- catalog entries as well, never randomly generated shop inventory.
insert into public.avatar_catalog (
  name, seed, gender_style, price_coins, required_level, rarity,
  is_active, is_starter, is_free, sort_order
)
values
  ('Ada', 'Ada', 'feminine', 0, 0, 'common', true, true, true, 10),
  ('Felix', 'Felix', 'masculine', 0, 0, 'common', true, true, true, 20),
  ('Nova', 'Nova', 'feminine', 0, 0, 'common', true, true, true, 30),
  ('Milo', 'Milo', 'masculine', 0, 0, 'common', true, true, true, 40),
  ('Sofia', 'Sofia', 'feminine', 0, 0, 'common', true, true, true, 50),
  ('Theo', 'Theo', 'masculine', 0, 0, 'common', true, true, true, 60),
  ('Luna', 'Luna', 'feminine', 0, 0, 'common', true, true, true, 70),
  ('Leo', 'Leo', 'masculine', 0, 0, 'common', true, true, true, 80),
  ('Maya', 'Maya', 'feminine', 0, 0, 'common', true, true, true, 90),
  ('Noah', 'Noah', 'masculine', 0, 0, 'common', true, true, true, 100),
  ('Iris', 'Iris', 'feminine', 0, 0, 'common', true, true, true, 110),
  ('Alex', 'Alex', 'masculine', 0, 0, 'common', true, true, true, 120),
  ('Atlas', 'Atlas', 'masculine', 5, 1, 'common', true, false, false, 210),
  ('Zara', 'Zara', 'feminine', 5, 1, 'common', true, false, false, 220),
  ('Orion', 'Orion', 'masculine', 10, 2, 'rare', true, false, false, 310),
  ('Freya', 'Freya', 'feminine', 10, 2, 'rare', true, false, false, 320),
  ('Kai', 'Kai', 'masculine', 15, 3, 'rare', true, false, false, 410),
  ('Lyra', 'Lyra', 'feminine', 15, 3, 'rare', true, false, false, 420),
  ('Vega', 'Vega', 'feminine', 0, 5, 'epic', true, false, true, 510),
  ('Jasper', 'Jasper', 'masculine', 25, 5, 'epic', true, false, false, 520),
  ('Astra', 'Astra', 'feminine', 0, 10, 'legendary', true, false, true, 610),
  ('Dorian', 'Dorian', 'masculine', 40, 10, 'legendary', true, false, false, 620)
on conflict (seed) do update set
  name = excluded.name,
  gender_style = excluded.gender_style,
  price_coins = excluded.price_coins,
  required_level = excluded.required_level,
  rarity = excluded.rarity,
  is_active = excluded.is_active,
  is_starter = excluded.is_starter,
  is_free = excluded.is_free,
  sort_order = excluded.sort_order;

-- Older profiles could have a selected starter only in Auth metadata. Preserve
-- that choice once before profiles.avatar becomes the sole display source.
update public.profiles p
set avatar = u.raw_user_meta_data ->> 'avatar'
from auth.users u
where u.id = p.id
  and p.avatar is null
  and u.raw_user_meta_data ->> 'avatar' in (
    select seed
    from public.avatar_catalog
    where is_starter
      and is_active
  );

-- Existing balances are initialized only once, so re-running this migration
-- cannot restore coins already spent by a user.
update public.profiles
set
  coin_balance = floor(greatest(coalesce(total_xp, 0), 0)::numeric / 10)::integer,
  total_coins_earned = floor(greatest(coalesce(total_xp, 0), 0)::numeric / 10)::integer,
  economy_initialized_at = now()
where economy_initialized_at is null;

-- The legacy fixed-seed CHECK cannot represent catalog ownership. Validation is
-- now performed by the guarded trigger and secure avatar RPC below.
alter table public.profiles
  drop constraint if exists profiles_avatar_check;

create or replace function public.guard_profile_economy()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  v_old_xp bigint;
  v_new_xp bigint;
  v_coins_earned integer;
  v_avatar_change_allowed boolean;
  v_economy_change_allowed boolean;
begin
  if tg_op = 'INSERT' then
    if auth.role() = 'authenticated' then
      if coalesce(new.total_xp, 0) <> 0
        or coalesce(new.coin_balance, 0) <> 0
        or coalesce(new.total_coins_earned, 0) <> 0 then
        raise exception 'Progresul economic nu poate fi setat din browser.';
      end if;

      if new.avatar is not null and not exists (
        select 1
        from public.avatar_catalog ac
        where ac.seed = new.avatar
          and ac.is_active
          and ac.is_starter
      ) then
        raise exception 'La crearea profilului poți selecta doar un avatar starter.';
      end if;
    end if;

    new.total_xp := greatest(coalesce(new.total_xp, 0), 0);
    new.coin_balance := greatest(coalesce(new.coin_balance, 0), 0);
    new.total_coins_earned := greatest(coalesce(new.total_coins_earned, 0), 0);
    new.economy_initialized_at := coalesce(new.economy_initialized_at, now());
    return new;
  end if;

  v_avatar_change_allowed := current_setting('app.pylearn_avatar_change', true) = 'on';
  v_economy_change_allowed := current_setting('app.pylearn_economy_change', true) = 'on';

  if auth.role() = 'authenticated' then
    if new.avatar is distinct from old.avatar and not v_avatar_change_allowed then
      raise exception 'Avatarul trebuie echipat din Shop sau din selectorul aprobat.';
    end if;

    if new.total_xp is distinct from old.total_xp
      or new.coin_balance is distinct from old.coin_balance
      or new.total_coins_earned is distinct from old.total_coins_earned
      or new.economy_initialized_at is distinct from old.economy_initialized_at then
      if not v_economy_change_allowed then
        raise exception 'Progresul economic nu poate fi modificat din browser.';
      end if;
    end if;
  end if;

  v_old_xp := greatest(coalesce(old.total_xp, 0), 0);
  v_new_xp := greatest(coalesce(new.total_xp, 0), 0);
  if v_new_xp < v_old_xp then
    raise exception 'XP-ul nu poate scădea.';
  end if;

  if v_new_xp > v_old_xp then
    v_coins_earned := (
      floor(v_new_xp::numeric / 10)::integer
      - floor(v_old_xp::numeric / 10)::integer
    );
    new.coin_balance := greatest(coalesce(old.coin_balance, 0), 0) + v_coins_earned;
    new.total_coins_earned := greatest(coalesce(old.total_coins_earned, 0), 0) + v_coins_earned;

    if v_coins_earned > 0 then
      insert into public.coin_transactions (user_id, amount, transaction_type, reason)
      values (old.id, v_coins_earned, 'earned', 'xp_reward');
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists profiles_guard_economy on public.profiles;
create trigger profiles_guard_economy
before insert or update on public.profiles
for each row execute function public.guard_profile_economy();

create or replace function public.buy_avatar(p_avatar_id bigint)
returns table (
  avatar_id bigint,
  avatar_seed text,
  coin_balance integer,
  total_coins_earned integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_avatar public.avatar_catalog%rowtype;
  v_total_xp bigint;
  v_coin_balance integer;
  v_total_coins integer;
  v_level integer;
begin
  if v_user_id is null then
    raise exception 'Trebuie să fii autentificat.';
  end if;

  select *
  into v_avatar
  from public.avatar_catalog
  where id = p_avatar_id
    and is_active;

  if not found then
    raise exception 'Avatarul nu este disponibil.';
  end if;

  if v_avatar.is_starter then
    raise exception 'Avatarul starter este disponibil gratuit.';
  end if;

  select
    coalesce(total_xp, 0),
    coalesce(coin_balance, 0),
    coalesce(total_coins_earned, 0)
  into v_total_xp, v_coin_balance, v_total_coins
  from public.profiles
  where id = v_user_id
  for update;

  if not found then
    raise exception 'Profilul tău nu a fost găsit.';
  end if;

  v_level := floor(greatest(v_total_xp, 0)::numeric / 100)::integer;
  if v_level < v_avatar.required_level then
    raise exception 'Nu ai încă nivelul necesar.';
  end if;

  if exists (
    select 1
    from public.user_avatars ua
    where ua.user_id = v_user_id
      and ua.avatar_id = v_avatar.id
  ) then
    raise exception 'Deții deja acest avatar.';
  end if;

  if v_coin_balance < v_avatar.price_coins then
    raise exception 'Nu ai suficiente monede.';
  end if;

  perform set_config('app.pylearn_economy_change', 'on', true);
  perform set_config('app.pylearn_economy_purchase', 'on', true);

  insert into public.user_avatars (user_id, avatar_id)
  values (v_user_id, v_avatar.id);

  update public.profiles
  set coin_balance = coin_balance - v_avatar.price_coins
  where id = v_user_id
  returning coin_balance, total_coins_earned
  into v_coin_balance, v_total_coins;

  if v_avatar.price_coins > 0 then
    insert into public.coin_transactions (user_id, amount, transaction_type, reason, reference_id)
    values (v_user_id, -v_avatar.price_coins, 'spent', 'avatar_purchase', v_avatar.id);
  end if;

  return query
  select v_avatar.id, v_avatar.seed::text, v_coin_balance, v_total_coins;
end;
$$;

create or replace function public.set_my_avatar(p_seed text)
returns table (avatar_seed text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_avatar public.avatar_catalog%rowtype;
  v_total_xp bigint;
  v_level integer;
begin
  if v_user_id is null then
    raise exception 'Trebuie să fii autentificat.';
  end if;

  select *
  into v_avatar
  from public.avatar_catalog
  where seed = p_seed
    and is_active;

  if not found then
    raise exception 'Avatarul nu este disponibil.';
  end if;

  select coalesce(total_xp, 0)
  into v_total_xp
  from public.profiles
  where id = v_user_id
  for update;

  if not found then
    raise exception 'Profilul tău nu a fost găsit.';
  end if;

  v_level := floor(greatest(v_total_xp, 0)::numeric / 100)::integer;
  if v_level < v_avatar.required_level then
    raise exception 'Nu ai încă nivelul necesar.';
  end if;

  if not v_avatar.is_starter and not exists (
    select 1
    from public.user_avatars ua
    where ua.user_id = v_user_id
      and ua.avatar_id = v_avatar.id
  ) then
    raise exception 'Trebuie să deții acest avatar înainte să îl echipezi.';
  end if;

  perform set_config('app.pylearn_avatar_change', 'on', true);
  update public.profiles
  set avatar = v_avatar.seed
  where id = v_user_id;

  return query select v_avatar.seed::text;
end;
$$;

alter table public.avatar_catalog enable row level security;
alter table public.user_avatars enable row level security;
alter table public.coin_transactions enable row level security;

drop policy if exists avatar_catalog_select_active on public.avatar_catalog;
create policy avatar_catalog_select_active
on public.avatar_catalog
for select
to authenticated
using (is_active);

drop policy if exists user_avatars_select_own on public.user_avatars;
create policy user_avatars_select_own
on public.user_avatars
for select
to authenticated
using (user_id = auth.uid());

-- The custom setting can only be established inside the secure purchase RPC;
-- normal browser inserts have no matching policy.
drop policy if exists user_avatars_insert_secure_purchase on public.user_avatars;
create policy user_avatars_insert_secure_purchase
on public.user_avatars
for insert
to authenticated
with check (
  user_id = auth.uid()
  and current_setting('app.pylearn_economy_purchase', true) = 'on'
);

drop policy if exists coin_transactions_select_own on public.coin_transactions;
create policy coin_transactions_select_own
on public.coin_transactions
for select
to authenticated
using (user_id = auth.uid());

drop policy if exists coin_transactions_insert_secure_purchase on public.coin_transactions;
create policy coin_transactions_insert_secure_purchase
on public.coin_transactions
for insert
to authenticated
with check (
  user_id = auth.uid()
  and current_setting('app.pylearn_economy_purchase', true) = 'on'
);

revoke all on table public.avatar_catalog from anon;
revoke all on table public.avatar_catalog from authenticated;
grant select on table public.avatar_catalog to authenticated;

revoke all on table public.user_avatars from anon;
revoke all on table public.user_avatars from authenticated;
grant select on table public.user_avatars to authenticated;
grant insert on table public.user_avatars to authenticated;

revoke all on table public.coin_transactions from anon;
revoke all on table public.coin_transactions from authenticated;
grant select on table public.coin_transactions to authenticated;
grant insert on table public.coin_transactions to authenticated;
grant usage on sequence public.coin_transactions_id_seq to authenticated;

revoke all on function public.buy_avatar(bigint) from public;
revoke all on function public.set_my_avatar(text) from public;
grant execute on function public.buy_avatar(bigint) to authenticated;
grant execute on function public.set_my_avatar(text) to authenticated;

notify pgrst, 'reload schema';
