-- Public profile data is exposed through narrowly-scoped RPCs instead of
-- broadening direct access to every column in public.profiles.
create or replace function public.get_public_profile(p_profile_id uuid)
returns table (
  id uuid,
  username text,
  avatar text,
  role text,
  grade_id bigint,
  grade_name text,
  total_xp integer,
  current_streak integer,
  longest_streak integer,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Trebuie să fii autentificat pentru a vedea un profil.';
  end if;

  return query
  select
    p.id::uuid,
    p.username::text,
    p.avatar::text,
    p.role::text,
    p.grade_id::bigint,
    g.name::text,
    coalesce(p.total_xp::integer, 0)::integer,
    coalesce(p.current_streak::integer, 0)::integer,
    coalesce(p.longest_streak::integer, 0)::integer,
    p.created_at::timestamptz
  from public.profiles p
  left join public.grades g on g.id = p.grade_id
  where p.id = p_profile_id;
end;
$$;

create or replace function public.get_public_solved_problem_count(p_profile_id uuid)
returns integer
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Trebuie să fii autentificat pentru a vedea progresul unui utilizator.';
  end if;

  return (
    select count(*)::integer
    from public.user_problem_status ups
    where ups.user_id = p_profile_id
      and ups.solved = true
  );
end;
$$;

create or replace function public.get_public_solved_problems(
  p_profile_id uuid,
  p_offset integer default 0,
  p_limit integer default 12
)
returns table (
  problem_id integer,
  title text,
  difficulty text,
  xp_reward integer,
  chapter_title text,
  chapter_section text,
  solved_at timestamp
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Trebuie să fii autentificat pentru a vedea progresul unui utilizator.';
  end if;

  return query
  select
    problem.id::integer,
    problem.title::text,
    problem.difficulty::text,
    coalesce(problem.xp_reward::integer, 0)::integer,
    chapter.title::text,
    chapter.section::text,
    ups.solved_at::timestamp
  from public.user_problem_status ups
  join public.problems problem on problem.id = ups.problem_id
  left join public.chapters chapter on chapter.id = problem.chapter_id
  where ups.user_id = p_profile_id
    and ups.solved = true
  order by ups.solved_at desc nulls last, ups.problem_id desc
  offset greatest(coalesce(p_offset, 0), 0)
  limit least(greatest(coalesce(p_limit, 12), 1), 50);
end;
$$;

revoke all on function public.get_public_profile(uuid) from public;
revoke all on function public.get_public_solved_problem_count(uuid) from public;
revoke all on function public.get_public_solved_problems(uuid, integer, integer) from public;
grant execute on function public.get_public_profile(uuid) to authenticated;
grant execute on function public.get_public_solved_problem_count(uuid) to authenticated;
grant execute on function public.get_public_solved_problems(uuid, integer, integer) to authenticated;

-- Keep the expanded avatar selector compatible with the profile constraint.
alter table public.profiles
  drop constraint if exists profiles_avatar_check;

alter table public.profiles
  add constraint profiles_avatar_check
  check (avatar is null or avatar in (
    'Ada', 'Felix', 'Nova', 'Milo', 'Sofia', 'Theo',
    'Luna', 'Leo', 'Maya', 'Noah', 'Iris', 'Alex'
  )) not valid;

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  title text not null,
  message text,
  link text,
  is_read boolean not null default false,
  classroom_id bigint references public.classrooms(id) on delete cascade,
  assignment_id bigint references public.assignments(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_created_at_idx
  on public.notifications (user_id, created_at desc);

create index if not exists notifications_user_read_idx
  on public.notifications (user_id, is_read);

create unique index if not exists notifications_new_assignment_unique_idx
  on public.notifications (user_id, assignment_id, type)
  where assignment_id is not null;

-- A published assignment is the only state that students can open. Delaying
-- the insert until publication also lets the frontend save its problem list first.
create or replace function public.notify_classroom_members_about_assignment()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_classroom_name text;
begin
  if not new.published then
    return new;
  end if;

  if tg_op = 'UPDATE' and old.published is not distinct from new.published then
    return new;
  end if;

  select name::text
  into v_classroom_name
  from public.classrooms
  where id = new.classroom_id;

  insert into public.notifications (
    user_id,
    type,
    title,
    message,
    link,
    classroom_id,
    assignment_id
  )
  select
    cm.student_id,
    'new_assignment',
    'Temă nouă',
    format(
      'Ai primit o temă nouă la clasa %s: „%s”.',
      coalesce(v_classroom_name, 'ta'),
      new.title
    ),
    '/teme/' || new.id,
    new.classroom_id,
    new.id
  from public.classroom_members cm
  where cm.classroom_id = new.classroom_id
  on conflict (user_id, assignment_id, type) where assignment_id is not null do nothing;

  return new;
end;
$$;

drop trigger if exists assignments_notify_classroom_members on public.assignments;
create trigger assignments_notify_classroom_members
after insert or update of published on public.assignments
for each row execute function public.notify_classroom_members_about_assignment();

alter table public.notifications enable row level security;

drop policy if exists notifications_select_own on public.notifications;
drop policy if exists notifications_update_own on public.notifications;

create policy notifications_select_own
on public.notifications
for select
to authenticated
using (user_id = auth.uid());

create policy notifications_update_own
on public.notifications
for update
to authenticated
using (user_id = auth.uid())
with check (user_id = auth.uid());

revoke all on table public.notifications from anon;
revoke all on table public.notifications from authenticated;
grant select on table public.notifications to authenticated;
grant update (is_read) on table public.notifications to authenticated;

revoke all on function public.notify_classroom_members_about_assignment() from public;

-- Realtime needs the table in the publication. This guard keeps the migration
-- safe if it is re-run after the table has already been published.
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
    and not exists (
      select 1
      from pg_publication_tables
      where pubname = 'supabase_realtime'
        and schemaname = 'public'
        and tablename = 'notifications'
    ) then
    alter publication supabase_realtime add table public.notifications;
  end if;
end;
$$;
