create table if not exists public.theory_lessons (
  id bigint generated by default as identity primary key,
  title text not null,
  slug text unique,
  content text not null,
  summary text,
  chapter_id integer not null references public.chapters(id) on delete cascade,
  order_index integer not null default 0,
  estimated_read_minutes integer check (estimated_read_minutes is null or estimated_read_minutes > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published boolean not null default true,
  difficulty text,
  thumbnail_url text,
  author_id uuid references public.profiles(id) on delete set null
);

create index if not exists theory_lessons_chapter_id_idx
  on public.theory_lessons (chapter_id);

create index if not exists theory_lessons_chapter_order_idx
  on public.theory_lessons (chapter_id, order_index, id);

create index if not exists theory_lessons_published_idx
  on public.theory_lessons (published);

create or replace function public.set_theory_lesson_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists theory_lessons_set_updated_at on public.theory_lessons;
create trigger theory_lessons_set_updated_at
before update on public.theory_lessons
for each row execute function public.set_theory_lesson_updated_at();

create table if not exists public.user_theory_progress (
  user_id uuid not null references public.profiles(id) on delete cascade,
  theory_id bigint not null references public.theory_lessons(id) on delete cascade,
  completed boolean not null default false,
  completed_at timestamptz,
  last_read_at timestamptz not null default now(),
  primary key (user_id, theory_id)
);

create index if not exists user_theory_progress_user_theory_idx
  on public.user_theory_progress (user_id, theory_id);

create or replace function public.is_theory_manager()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles
    where id = auth.uid()
      and role in ('profesor', 'teacher')
  );
$$;

create or replace function public.complete_theory_lesson(p_theory_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then
    raise exception 'Trebuie să fii autentificat pentru a marca o lecție ca parcursă.';
  end if;

  if not exists (
    select 1
    from public.theory_lessons
    where id = p_theory_id
      and published = true
  ) then
    raise exception 'Lecția nu este disponibilă.';
  end if;

  insert into public.user_theory_progress (user_id, theory_id, completed, completed_at, last_read_at)
  values (auth.uid(), p_theory_id, true, now(), now())
  on conflict (user_id, theory_id) do update
  set
    completed = true,
    completed_at = coalesce(public.user_theory_progress.completed_at, now()),
    last_read_at = now();
end;
$$;

alter table public.theory_lessons enable row level security;
alter table public.user_theory_progress enable row level security;

drop policy if exists theory_lessons_select_anon on public.theory_lessons;
drop policy if exists theory_lessons_select_authenticated on public.theory_lessons;
drop policy if exists theory_lessons_insert_managers on public.theory_lessons;
drop policy if exists theory_lessons_update_managers on public.theory_lessons;
drop policy if exists theory_lessons_delete_managers on public.theory_lessons;
drop policy if exists user_theory_progress_select_own on public.user_theory_progress;

create policy theory_lessons_select_anon
on public.theory_lessons
for select
to anon
using (published = true);

create policy theory_lessons_select_authenticated
on public.theory_lessons
for select
to authenticated
using (published = true or public.is_theory_manager());

create policy theory_lessons_insert_managers
on public.theory_lessons
for insert
to authenticated
with check (public.is_theory_manager());

create policy theory_lessons_update_managers
on public.theory_lessons
for update
to authenticated
using (public.is_theory_manager())
with check (public.is_theory_manager());

create policy theory_lessons_delete_managers
on public.theory_lessons
for delete
to authenticated
using (public.is_theory_manager());

create policy user_theory_progress_select_own
on public.user_theory_progress
for select
to authenticated
using (user_id = auth.uid());

revoke all on table public.theory_lessons from anon;
revoke all on table public.theory_lessons from authenticated;
revoke all on table public.user_theory_progress from anon;
revoke all on table public.user_theory_progress from authenticated;
grant select on table public.theory_lessons to anon, authenticated;
grant insert, update, delete on table public.theory_lessons to authenticated;
grant select on table public.user_theory_progress to authenticated;
revoke all on function public.is_theory_manager() from public;
grant execute on function public.is_theory_manager() to authenticated;
revoke all on function public.complete_theory_lesson(bigint) from public;
grant execute on function public.complete_theory_lesson(bigint) to authenticated;
